[wxflows.deployment]
endpoint_name = "api/langchain-toolcalling"
# Example flows.
flows="  // You should add your flows here "
ai_engine = "WATSONX"



# Endpoint imports provide customized extensions for your flows
[[wxflows.deployment.endpoint.imports]]
# import 1
name = "google_books"
package = "google_books.zip"

[[wxflows.deployment.endpoint.imports.tools]] # import 1: tool description 1
name = "google_books"
description = """Retrieve information from Google Books. Find books by search string, for example to search for Daniel Keyes 'Flowers for Algernon' use q: 'intitle:flowers+inauthor:keyes'"""
fields = "books|book"

[[wxflows.deployment.endpoint.imports]]
# import 2
name = "wikipedia"
package = "wikipedia.zip"

[[wxflows.deployment.endpoint.imports.tools]] # import 2: tool description 1
name = "wikipedia"
description = """Retrieve information from Wikipedia."""
fields = "search|page"

